// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = never;

/**
 * Content for about documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *about*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Meta Description field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *about*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * about document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, 'about', Lang>;

type AwardDocumentDataSlicesSlice = never;

/**
 * Content for award documents
 */
interface AwardDocumentData {
  /**
   * Slice Zone field in *award*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: award.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AwardDocumentDataSlicesSlice>
  /**
   * Meta Description field in *award*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: award.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *award*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: award.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *award*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: award.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * award document from Prismic
 *
 * - **API ID**: `award`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AwardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AwardDocumentData>, 'award', Lang>;

type BlogDocumentDataSlicesSlice = BreadcrumbSlice;

/**
 * Content for blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>
  /**
   * Meta Description field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, 'blog', Lang>;

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>
  /**
   * Meta Description field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    'contact',
    Lang
  >;

type GalleryDocumentDataSlicesSlice = never;

/**
 * Content for gallery documents
 */
interface GalleryDocumentData {
  /**
   * Slice Zone field in *gallery*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GalleryDocumentDataSlicesSlice>
  /**
   * Meta Description field in *gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: gallery.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: gallery.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GalleryDocumentData>,
    'gallery',
    Lang
  >;

type HomepageDocumentDataSlicesSlice = LandingSlice | HeroSlice | BlogSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >;

type TeamsDocumentDataSlicesSlice = never;

/**
 * Content for teams documents
 */
interface TeamsDocumentData {
  /**
   * Slice Zone field in *teams*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: teams.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeamsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *teams*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: teams.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *teams*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teams.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *teams*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: teams.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * teams document from Prismic
 *
 * - **API ID**: `teams`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TeamsDocumentData>, 'teams', Lang>;

type UrucupDocumentDataSlicesSlice = never;

/**
 * Content for urucup documents
 */
interface UrucupDocumentData {
  /**
   * Slice Zone field in *urucup*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: urucup.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<UrucupDocumentDataSlicesSlice>
  /**
   * Meta Description field in *urucup*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: urucup.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *urucup*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: urucup.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *urucup*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: urucup.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * urucup document from Prismic
 *
 * - **API ID**: `urucup`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UrucupDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<UrucupDocumentData>, 'urucup', Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | AwardDocument
  | BlogDocument
  | ContactDocument
  | GalleryDocument
  | HomepageDocument
  | TeamsDocument
  | UrucupDocument;

/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Blog*
 */
type BlogSliceVariation = BlogSliceDefault;

/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Blog
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSlice = prismic.SharedSlice<'blog', BlogSliceVariation>;

/**
 * Default variation for Breadcrumb Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BreadcrumbSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Breadcrumb*
 */
type BreadcrumbSliceVariation = BreadcrumbSliceDefault;

/**
 * Breadcrumb Shared Slice
 *
 * - **API ID**: `breadcrumb`
 * - **Description**: Breadcrumb
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BreadcrumbSlice = prismic.SharedSlice<
  'breadcrumb',
  BreadcrumbSliceVariation
>;

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>;

/**
 * slider variation for Hero Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlider = prismic.SharedSliceVariation<
  'slider',
  Record<string, never>,
  never
>;

/**
 * video variation for Hero Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceVideo = prismic.SharedSliceVariation<
  'video',
  Record<string, never>,
  never
>;

/**
 * internal variation for Hero Slice
 *
 * - **API ID**: `internal`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceInternal = prismic.SharedSliceVariation<
  'internal',
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceSlider
  | HeroSliceVideo
  | HeroSliceInternal;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Default variation for InternalHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InternalHeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>;

/**
 * Slice variation for *InternalHero*
 */
type InternalHeroSliceVariation = InternalHeroSliceDefault;

/**
 * InternalHero Shared Slice
 *
 * - **API ID**: `internal_hero`
 * - **Description**: InternalHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InternalHeroSlice = prismic.SharedSlice<
  'internal_hero',
  InternalHeroSliceVariation
>;

/**
 * Primary content in *Landing → Primary*
 */
export interface LandingSliceDefaultPrimary {
  /**
   * title field in *Landing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * logo field in *Landing → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * social_youtube field in *Landing → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.primary.social_youtube
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_youtube: prismic.LinkField;

  /**
   * social_instagram field in *Landing → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.primary.social_instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_instagram: prismic.LinkField;

  /**
   * social_linkedin field in *Landing → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.primary.social_linkedin
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_linkedin: prismic.LinkField;
}

/**
 * Default variation for Landing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LandingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Landing*
 */
type LandingSliceVariation = LandingSliceDefault;

/**
 * Landing Shared Slice
 *
 * - **API ID**: `landing`
 * - **Description**: Landing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingSlice = prismic.SharedSlice<
  'landing',
  LandingSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AwardDocument,
      AwardDocumentData,
      AwardDocumentDataSlicesSlice,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      GalleryDocument,
      GalleryDocumentData,
      GalleryDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      TeamsDocument,
      TeamsDocumentData,
      TeamsDocumentDataSlicesSlice,
      UrucupDocument,
      UrucupDocumentData,
      UrucupDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogSlice,
      BlogSliceVariation,
      BlogSliceDefault,
      BreadcrumbSlice,
      BreadcrumbSliceVariation,
      BreadcrumbSliceDefault,
      HeroSlice,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSlider,
      HeroSliceVideo,
      HeroSliceInternal,
      InternalHeroSlice,
      InternalHeroSliceVariation,
      InternalHeroSliceDefault,
      LandingSlice,
      LandingSliceDefaultPrimary,
      LandingSliceVariation,
      LandingSliceDefault,
    };
  }
}
