// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  blog: dynamic(() => import('./Blog')),
  breadcrumb: dynamic(() => import('./Breadcrumb')),
  hero: dynamic(() => import('./Hero')),
  internal_hero: dynamic(() => import('./InternalHero')),
  landing: dynamic(() => import('./Landing')),
};
